sudo: false

language: python

python:
  - 2.7
  - 3.5

before_install:
  - pip install --upgrade pip setuptools
  - pip install coveralls

install:
  - python setup.py sdist
  - pip install dist/omega-*.tar.gz

script:
  - cd tests/
  - nosetests --with-coverage --cover-package=omega

after_success:
  - coveralls
