sudo: false

language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

before_install:
  - pip install --upgrade pip setuptools
  - pip install coveralls

install:
  - python setup.py sdist
  - pip install dist/omega-*.tar.gz

script:
  - cd tests/
  - nosetests -e "cover*"
  - cd ..
  # install `dd.cudd`
  - pip uninstall --yes dd
  - pip download --no-dependencies dd>=0.5.2 --no-binary dd
  - tar xzf dd-*.tar.gz
  - cd dd-*/
  - python setup.py install --fetch --cudd
  - cd ..
  - cd tests/
  - nosetests --with-coverage --cover-package=omega

after_success:
  - coveralls
